_prefs: 
  mapid: enf.1a78aa2a
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "Data from the Flickr search API. Base map <a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -0.1124
  - 51.4996
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: The Geotaggers' World Atlas
source: "mapbox:///mapbox.mapbox-streets-v5,enf.u2uzncdi"
styles: 
  - style.mss
template: ''
